import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

export default
{
  // MIDI Tab
  midiSidebar:
  [
    {
      label: 'SysEx Messages',
      type: 'category',
      link: {
        type: 'doc',
        id: 'sysex/index',
      },
      collapsible: true,
      collapsed: false,
      items:
      [
        'sysex/master-volume',
        'sysex/master-fine-tune',
        'sysex/master-coarse-tune',
      ],
    },
    {
      label: 'RPNs',
      type: 'category',
      link: {
        type: 'doc',
        id: 'rpns/index',
      },
      collapsible: true,
      collapsed: false,
      items:
      [
        'rpns/pitch-bend-sensitivity',
        'rpns/channel-fine-tune',
        'rpns/channel-coarse-tune',
      ],
    },
    'programs',
    'note-division',
    // {
    //   label: 'MIDI',
    //   type: 'category',
    //   collapsible: false,
    //   collapsed: false,
    //   items: [
    //     'sysex',
    //     'rpns',
    //     'programs',
    //     'note-division',
    //   ],
    // },
  ],

  // Auto-generated MIDI Tab Sidebar
  // docs:
  // [
  //   {
  //     type: 'autogenerated',
  //     dirName: '.',
  //   },
  // ],

} satisfies SidebarsConfig;