import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

export default
{
  // Getting Started Tab
  gettingStartedSidebar:
  [
    // {
    //   label: 'Getting Started',
    //   type: 'category',
    //   link:
    //   {
    //     type: 'generated-index',
    //   },
    //   collapsible: false,
    //   collapsed: false,
    //   items:
    //   [
    //     'glossary',
    //   ],
    // },

    {
      label: 'ROM File',
      type: 'category',
      link:
      {
        type: 'generated-index',
      },
      collapsible: true,
      collapsed: false,
      items:
      [
        'rom/checksum',
        'rom/byte-order',
        'rom/decompression',
      ],
    },

    'glossary',
  ],

  // Auto-generated Getting Started Tab Sidebar
  // docs:
  // [
  //   {
  //     type: 'autogenerated',
  //     dirName: '.',
  //   },
  // ],

} satisfies SidebarsConfig;