import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

export default
{
  aseqMessagesSidebar:
  [
    'message-format',
    // Control Flow
    {
      type: 'category',
      label: 'Control Flow',
      link:
      {
        type: 'generated-index',
      },
      collapsible: true,
      collapsed: true,
      items:
      [
        'control-flow/RBLTZ',
        'control-flow/RBEQZ',
        'control-flow/RJUMP',
        'control-flow/BGEZ',
        'control-flow/BREAK',
        'control-flow/LOOPEND',
        'control-flow/LOOP',
        'control-flow/BLTZ',
        'control-flow/BEQZ',
        'control-flow/JUMP',
        'control-flow/CALL',
        'control-flow/DELAY',
        'control-flow/DELAY1',
        'control-flow/END',
        // {
        //   type: 'autogenerated',
        //   dirName: 'control-flow',
        // },
      ],
    },

    // Header
    {
      type: 'category',
      label: 'Header',
      link:
      {
        type: 'generated-index',
      },
      collapsible: true,
      collapsed: true,
      items:
      [
        'header/TESTCHAN',
        'header/STOPCHAN',
        'header/SUBIO',
        'header/LDRES',
        'header/STIO',
        'header/LDIO',
        'header/LDCHAN',
        'header/RLDCHAN',
        'header/LDSEQ',
        'header/C2',
        'header/MUTECHAN',
        'header/RUNSEQ',
        'header/SCRIPTCTR',
        'header/STOP',
        'header/STSEQ',
        'header/SUB',
        'header/AND',
        'header/LDI',
        'header/DYNCALL',
        'header/RAND',
        'header/NOTEALLOC',
        'header/LDSHORTGATEARR',
        'header/LDSHORTVELARR',
        'header/MUTEBHV',
        'header/MUTE',
        'header/MUTESCALE',
        'header/FREECHAN',
        'header/INITCHAN',
        'header/VOLSCALE',
        'header/VOLMODE',
        'header/VOL',
        'header/TEMPOCHG',
        'header/TEMPO',
        'header/RTRANSPOSE',
        'header/TRANSPOSE',
        'header/PRINT3',
        'header/FREENOTELIST',
        'header/ALLOCNOTELIST',
        // {
        //   type: 'autogenerated',
        //   dirName: 'header',
        // },
      ],
    },

    // Channel
    {
      type: 'category',
      label: 'Channel',
      link:
      {
        type: 'generated-index',
      },
      collapsible: true,
      collapsed: true,
      items:
      [
        'channel/CDELAY',
        'channel/LDSAMPLE',
        'channel/LDCHAN',
        'channel/STCIO',
        'channel/LDCIO',
        'channel/SUBIO',
        'channel/LDIO',
        'channel/STIO',
        'channel/RLDLAYER',
        'channel/TESTLAYER',
        'channel/LDLAYER',
        'channel/DELLAYER',
        'channel/DYNLDLAYER',
        'channel/A0',
        'channel/A1',
        'channel/A2',
        'channel/A3',
        'channel/A4',
        'channel/A5',
        'channel/A6',
        'channel/A7',
        'channel/RANDPTR',
        'channel/LDFILTER',
        'channel/FREEFILTER',
        'channel/LDSEQTOPTR',
        'channel/FILTER',
        'channel/PTRTODYNTBL',
        'channel/DYNTBLTOPTR',
        'channel/DYNTBLV',
        'channel/RANDTOPTR',
        'channel/RAND',
        'channel/RANDVEL',
        'channel/RANDGATE',
        'channel/COMBFILTER',
        'channel/PTRADD',
        'channel/SAMPLESTART',
        'channel/BE',
        'channel/INSTR',
        'channel/DYNTBL',
        'channel/NOLEGATO',
        'channel/LEGATO',
        'channel/DYNTBLLOOKUP',
        'channel/FONT',
        'channel/STSEQ',
        'channel/SUB',
        'channel/AND',
        'channel/MUTEBHV',
        'channel/LDSEQ',
        'channel/LDI',
        'channel/STOPCHAN',
        'channel/LDPTR',
        'channel/STPTRTOSEQ',
        'channel/EFFECTS',
        'channel/NOTEALLOC',
        'channel/SUSTAIN',
        'channel/BEND',
        'channel/REVERB',
        'channel/VIBFREQ',
        'channel/VIBDEPTH',
        'channel/RELEASERATE',
        'channel/ENV',
        'channel/TRANSPOSE',
        'channel/PANWEIGHT',
        'channel/PAN',
        'channel/FREQSCALE',
        'channel/VOL',
        'channel/VOLEXP',
        'channel/VIBFREQGRAD',
        'channel/VIBDEPTHGRAD',
        'channel/VIBDELAY',
        'channel/DYNCALL',
        'channel/REVERBIDX',
        'channel/SAMPLEBOOK',
        'channel/LDPARAMS',
        'channel/PARAMS',
        'channel/NOTEPRI',
        'channel/STOP',
        'channel/FONTINSTR',
        'channel/VIBRESET',
        'channel/GAIN',
        'channel/BENDFINE',
        'channel/FREENOTELIST',
        'channel/ALLOCNOTELIST',
        // {
        //   type: 'autogenerated',
        //   dirName: 'channel',
        // },
      ],
    },

    // Note Layer
    {
      type: 'category',
      label: 'Note Layer',
      link:
      {
        type: 'generated-index',
      },
      collapsible: true,
      collapsed: true,
      items:
      [
        'layer/NOTEDVG',
        'layer/NOTEDV',
        'layer/NOTEVG',
        'layer/LDELAY',
        'layer/SHORTVEL',
        'layer/TRANSPOSE',
        'layer/SHORTDELAY',
        'layer/LEGATO',
        'layer/NOLEGATO',
        'layer/INSTR',
        'layer/PORTAMENTO',
        'layer/NOPORTAMENTO',
        'layer/SHORTGATE',
        'layer/NOTEPAN',
        'layer/ENV',
        'layer/NODRUMPAN',
        'layer/STEREO',
        'layer/BENDFINE',
        'layer/RELEASERATE',
        'layer/LDSHORTVEL',
        'layer/LDSHORTGATE',
        'layer/F0',
        'layer/F1',
        // {
        //   type: 'autogenerated',
        //   dirName: 'layer',
        // },
      ],
    },
  ],

  // Auto-generated MIDI Tab Sidebar
  // docs:
  // [
  //   {
  //     type: 'autogenerated',
  //     dirName: '.',
  //   },
  // ],

} satisfies SidebarsConfig;