import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

export default
{
  // Documentation Tab
  docsSidebar:
  [
    // Audio Sequences
    {
      label: 'Audio Sequences',
      type: 'category',
      link:
      {
        type: 'generated-index',
      },
      collapsible: true,
      collapsed: false,
      items:
      [
        'audio-sequences/limitations',
        'audio-sequences/looping',
        'audio-sequences/voice-allocation',
      ],
    },

    // Instruments
    {
      label: 'Instruments',
      type: 'category',
      link:
      {
        type: 'generated-index',
      },
      collapsible: true,
      collapsed: false,
      items:
      [
        'instruments/types',
        'instruments/assignment',
        'instruments/pitch-range',
        'instruments/envelopes'
      ],
    },

    // Instrument Banks
    {
      label: 'Instrument Banks',
      type: 'category',
      link:
      {
        type: 'generated-index',
      },
      collapsible: true,
      collapsed: false,
      items:
      [
        'instrument-banks/index-entry',
        'instrument-banks/instrument',
        'instrument-banks/drum',
        'instrument-banks/sample',
        'instrument-banks/loopbook',
        'instrument-banks/codebook',
        'instrument-banks/envelope',
      ],
    },

    // Audio Samples
    {
      label: 'Audio Samples',
      type: 'category',
      link:
      {
        type: 'generated-index',
      },
      collapsible: true,
      collapsed: false,
      items:
      [
        'audio-samples/vadpcm',
        'audio-samples/tuning',
      ],
    },

    // Music Files
    {
      label: 'Music Files',
      type: 'category',
      link:
      {
        type: 'generated-index',
      },
      collapsible: true,
      collapsed: false,
      items:
      [
        'music-files/metadata',
        'music-files/music-groups',
        'music-files/formmask',
      ],
    },
  ],

  // Auto-generated Documentation Tab Sidebar
  // docs:
  // [
  //   {
  //     type: 'autogenerated',
  //     dirName: '.',
  //   },
  // ],

} satisfies SidebarsConfig;