import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

export default
{
  // MIDI Tab
  midiSidebar:
  [
    'sysex',
    'rpns',
    'programs',
    'note-division',
    // {
    //   label: 'MIDI',
    //   type: 'category',
    //   collapsible: false,
    //   collapsed: false,
    //   items: [
    //     'sysex',
    //     'rpns',
    //     'programs',
    //     'note-division',
    //   ],
    // },
  ],

  // Auto-generated MIDI Tab Sidebar
  // docs:
  // [
  //   {
  //     type: 'autogenerated',
  //     dirName: '.',
  //   },
  // ],

} satisfies SidebarsConfig;