import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

export default
{
  // Guides Tab
  guidesSidebar:
  [
    // SEQ64
    {
      label: 'SEQ64',
      type: 'category',
      link:
      {
        type: 'generated-index',
      },
      collapsible: true,
      collapsed: false,
      items: [
        'seq64/errors',
      ],
    },

    // Audio Sampling
    {
      label: 'Custom Samples',
      type: 'category',
      link:
      {
        type: 'generated-index',
      },
      collapsible: true,
      collapsed: false,
      items: [
        'sampling/conversion',
        'sampling/resampling',
        'sampling/pitch-shifting',
        'sampling/looping',
      ],
    },
  ],

  // Auto-generated Guides Tab Sidebar
  // docs:
  // [
  //   {
  //     type: 'autogenerated',
  //     dirName: '.',
  //   },
  // ],

} satisfies SidebarsConfig;